{{- if and .Values.secret.create (not .Values.secret.existingSecret) -}}
{{- $secretName := include "vc-common-service.secretName" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "vc-common-service.labels" . | nindent 4 }}
  {{- if .Values.secret.retainOnUninstall }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
